[package]
name = "uowji-report-template"
description = "A Typst template to quickly scaffold a report for your projects, forked from red-agora"
version = "0.1.0"
entrypoint = "lib.typ"
license = "MIT"
authors = ["Lzzzt"]
categories = ["report"]
keywords = ["report", "template"]
exclude = ["example.pdf"]
repository = "https://github.com/Lzzzzzt/report-template.git"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template/thumbnail.png"
